/**
 * Development-only harness: renders the monthly PDF from fixture data so the
 * layout, Thai typography and signature placement can be checked without
 * seeding Firebase. Open http://localhost:5173/pdf-preview.html while `npm run
 * dev` is running. It is not linked from the app and is not part of the build.
 */
import { buildMonthlyReport } from '@/utils/pdf/monthlyReport';
import { SUPERVISION_CATEGORIES } from '@/config/constants';
import type { SupervisionRecord, UserProfile } from '@/types';

const profile: UserProfile = {
  uid: 'demo-user',
  fullName: 'นายณัฐวัฒน์ วรรณชัย',
  position: 'ศึกษานิเทศก์',
  academicStanding: 'ชำนาญการพิเศษ',
  department: 'กลุ่มนิเทศ ติดตาม และประเมินผลการจัดการศึกษา',
  email: 'demo@sukhothai2.go.th',
  phone: '0987491344',
  lineId: 'xdeathxsign',
  signatureUrl: signatureDataUrl(),
  signaturePath: null,
  role: 'supervisor',
  createdAt: null,
  updatedAt: null,
};

const SAMPLE = [
  ['การนิเทศการจัดการเรียนรู้เชิงรุก (Active Learning)', 'โรงเรียนบ้านสวรรคโลก', 0],
  ['การนิเทศการอ่านออกเขียนได้ ชั้น ป.1-ป.3', 'โรงเรียนวัดคลองกระจง', 4],
  ['การนิเทศหลักสูตรสถานศึกษาและการวัดผล', 'โรงเรียนอนุบาลศรีสำโรง', 1],
  ['การติดตามการประกันคุณภาพภายในสถานศึกษา', 'โรงเรียนบ้านท่าชัย', 3],
  ['การนิเทศการใช้สื่อเทคโนโลยีเพื่อการเรียนรู้', 'โรงเรียนบ้านหนองบัว', 6],
  ['การติดตามผลการดำเนินงานตามนโยบายเร่งด่วน', 'โรงเรียนบ้านวังไม้ขอน', 7],
] as const;

const records: SupervisionRecord[] = SAMPLE.map(([topic, location, categoryIndex], index) => {
  const day = String(3 + index * 4).padStart(2, '0');

  return {
    id: `demo-${index}`,
    userId: profile.uid,
    supervisorName: profile.fullName,
    supervisorPosition: profile.position,
    category: SUPERVISION_CATEGORIES[categoryIndex],
    topic,
    location,
    content:
      'ผู้บริหารและคณะครูให้ความร่วมมือเป็นอย่างดี ครูจัดกิจกรรมการเรียนรู้ที่เน้นผู้เรียนเป็นสำคัญ ' +
      'มีการใช้สื่อและแหล่งเรียนรู้ที่หลากหลาย ข้อเสนอแนะ ควรเพิ่มการวัดและประเมินผลตามสภาพจริง ' +
      'และจัดทำวิจัยในชั้นเรียนเพื่อพัฒนาผู้เรียนอย่างต่อเนื่อง',
    startDate: `2025-06-${day}`,
    endDate: `2025-06-${day}`,
    startTime: '09:00',
    endTime: '16:30',
    images: index < 3 ? [photo(`ภาพที่ ${index + 1}`, index)] : [],
    monthKey: '2025-06',
    year: 2025,
    month: 6,
    createdAt: null,
    updatedAt: null,
  };
});

async function render() {
  const status = document.getElementById('status');
  const frame = document.getElementById('frame') as HTMLIFrameElement | null;

  if (status) {
    status.textContent = 'กำลังสร้าง...';
  }

  const { doc } = await buildMonthlyReport({ profile, records, monthKey: '2025-06' });
  const url = doc.output('bloburl');

  if (frame) {
    frame.src = String(url);
  }

  if (status) {
    status.textContent = `สร้างสำเร็จ • ${doc.getNumberOfPages()} หน้า`;
  }

  // Exposed so an automated check can assert on the generated bytes.
  (window as unknown as { __pdf?: string }).__pdf = doc.output('datauristring');
}

document.getElementById('rebuild')?.addEventListener('click', () => void render());
void render();

/** A scribbled signature, drawn on a transparent canvas. */
function signatureDataUrl(): string {
  const canvas = document.createElement('canvas');

  canvas.width = 420;
  canvas.height = 140;

  const context = canvas.getContext('2d');

  if (context) {
    context.strokeStyle = '#111827';
    context.lineWidth = 4;
    context.lineCap = 'round';
    context.beginPath();
    context.moveTo(30, 100);
    context.bezierCurveTo(90, 10, 130, 130, 190, 60);
    context.bezierCurveTo(240, 10, 250, 120, 320, 70);
    context.lineTo(390, 90);
    context.stroke();
  }

  return canvas.toDataURL('image/png');
}

/** A placeholder photo so the appendix has something to lay out. */
function photo(label: string, seed: number): SupervisionRecord['images'][number] {
  const canvas = document.createElement('canvas');

  canvas.width = 960;
  canvas.height = 640;

  const context = canvas.getContext('2d');

  if (context) {
    const gradient = context.createLinearGradient(0, 0, 960, 640);

    gradient.addColorStop(0, ['#34D399', '#5EEAD4', '#A7F3D0'][seed % 3]);
    gradient.addColorStop(1, ['#0F766E', '#047857', '#0D9488'][seed % 3]);
    context.fillStyle = gradient;
    context.fillRect(0, 0, 960, 640);
    context.fillStyle = '#ffffff';
    context.font = 'bold 56px Kanit, sans-serif';
    context.textAlign = 'center';
    context.fillText(label, 480, 340);
  }

  return { url: canvas.toDataURL('image/jpeg', 0.8), path: `demo/${seed}`, name: label, size: 250 * 1024 };
}
